### ISSUE TITLE
missing init data

### ISSUE THREAD

**Issue by gitconur** [Amos-Chen98/Gap-gradient-based-search_ECMI-Modelling-Week2020_Q1#1]
Hi Chen, could you please include the .slv and .dat files to the repo?

![image](https://user-images.githubusercontent.com/82085788/215774185-9078767d-42ad-40bd-b1dc-eaa48f4c2cad.png)

**Comment by Amos-Chen98** [comment]
Hello @gitconur , unfortunately, the data is no longer accessible. Sorry for this.
